In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_excel(r"C:\Users\ANSHIKA\Downloads\c1f5fb48-ba6c-4464-919d-4aba384c7c80.xlsx")
df

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Performance,Email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [4]:
df.head(10)

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Performance,Email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
5,1006,Deepa,27,F,HR,"48,000",NaN,15/02/2022,NaN,NaN
6,1007,Priya,Thirty,NaN,NaN,NaN,Bangalore,2024/03/01,NaN,invalidemail
7,1008,Aisha,27,NaN,Marketing,"48,000",NaN,2023-01-15,Excellent,invalidemail
8,1009,Mohammed,NaN,M,NaN,55000,NaN,2023-01-15,NaN,user@example.com
9,1010,Mohammed,25,F,HR,"48,000",Bangalore,NaN,NaN,invalidemail

In [5]:
df.tail(10)

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Performance,Email
90,1091,Aisha,22,M,Sales,35000,Calicut,15/02/2022,good,invalidemail
91,1092,Kiran,NaN,F,Finance,55000,NaN,NaN,Poor,user@example.com
92,1093,Mohammed,Thirty,Male,NaN,55000,Kochi,NaN,Good,NaN
93,1094,Arun,22,F,Sales,35000,Calicut,2024/03/01,Excellent,test@mail.com
94,1095,Deepa,25,Male,Marketing,"48,000",NaN,2024/03/01,good,NaN
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [6]:
df.describe()

        EmployeeID
count   100.000000
mean   1050.400000
std      29.151988
min    1001.000000
25%    1025.750000
50%    1050.500000
75%    1075.250000
max    1100.000000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   100 non-null    int64
 1   Name         100 non-null    str
 2   Age          82 non-null     object
 3   Gender       75 non-null     str
 4   Department   85 non-null     str
 5   Salary       77 non-null     object
 6   City         70 non-null     str
 7   JoinDate     83 non-null     str
 8   Performance  81 non-null     str
 9   Email        75 non-null     str
dtypes: int64(1), object(2), str(7)
memory usage: 7.9+ KB

In [8]:
df.nunique()

EmployeeID     99
Name           18
Age             6
Gender          4
Department      6
Salary          4
City            5
JoinDate        3
Performance     4
Email           3
dtype: int64

In [11]:
df.isnull()

,EmployeeID,Name,Age,Gender,Department,Salary,City,JoinDate,Performance,Email
0,False,False,False,False,True,False,False,True,False,False
1,False,False,False,False,False,True,False,False,True,False
2,False,False,False,False,False,False,True,True,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,True
96,False,False,False,False,False,False,True,False,False,False
97,False,False,False,False,False,True,True,True,False,False
98,False,False,False,False,False,False,False,False,True,False
99,False,False,False,False,False,False,True,False,False,False

In [12]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [13]:
df.duplicated("EmployeeID")

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [35]:
df.columns=df.columns.str.lower()
df

,e m p l o y e e i d,n a m e,a g e,g e n d e r,d e p a r t m e n t,s a l a r y,c i t y,j o i n d a t e,p e r f o r m a n c e,e m a i l
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [36]:
print(df.columns)

Index(['   e   m   p   l   o   y   e   e   i   d   ', '   n   a   m   e   ',
       '   a   g   e   ', '   g   e   n   d   e   r   ',
       '   d   e   p   a   r   t   m   e   n   t   ',
       '   s   a   l   a   r   y   ', '   c   i   t   y   ',
       '   j   o   i   n   d   a   t   e   ',
       '   p   e   r   f   o   r   m   a   n   c   e   ',
       '   e   m   a   i   l   '],
      dtype='str')

In [37]:
print(repr(df.columns[0]))

'   e   m   p   l   o   y   e   e   i   d   '

In [38]:
df.columns = [''.join(col.split()) for col in df.columns]

In [39]:

df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [41]:
df.columns = df.columns.str.lower().str.replace(" ", "_", regex=False)
df

,employeeid,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [46]:
df.rename(columns={"employeeid": "Employee_Id"}, inplace=True)
df

,Employee_Id,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [47]:
df.rename(columns={"joindate": "Join Date"})
df

,Employee_Id,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [48]:
df.columns = df.columns.str.replace(" ", "_")
df

,Employee_Id,name,age,gender,department,salary,city,joindate,performance,email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [49]:
df.columns=df.columns.str.title()
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,NaN,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [51]:
df.isnull().sum()

Employee_Id     0
Name            0
Age            18
Gender         25
Department     15
Salary         23
City           30
Joindate       17
Performance    19
Email          25
dtype: int64

In [54]:
df.dtypes

Employee_Id     int64
Name              str
Age            object
Gender            str
Department        str
Salary         object
City              str
Joindate          str
Performance       str
Email             str
dtype: object

In [58]:
df["Gender"] = df["Gender"].fillna("Unknown")
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,NaN,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [69]:
df["Department"] = df["Department"].fillna("Unknown")
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",NaN,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,"48,000",NaN,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,NaN,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,NaN,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,NaN,2023-01-15,Poor,invalidemail

In [66]:
df["Salary"].dtype

dtype('O')

In [67]:
df["Salary"].unique()

array([55000, nan, '48,000', 35000, 42000], dtype=object)

In [70]:
df["City"] = df["City"].fillna("Unknown")
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,NaN,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",Unknown,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,"48,000",Unknown,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,Unknown,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,Unknown,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,NaN,invalidemail
99,1100,Sara,31,Female,IT,55000,Unknown,2023-01-15,Poor,invalidemail

In [72]:
df["Performance"] = df["Performance"].fillna("Unknown")
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,Unknown,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",Unknown,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,"48,000",Unknown,15/02/2022,Good,NaN
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,NaN
96,1097,Mohammed,29,Male,HR,35000,Unknown,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,Unknown,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,Unknown,invalidemail
99,1100,Sara,31,Female,IT,55000,Unknown,2023-01-15,Poor,invalidemail

In [74]:
df["Email"] = df["Email"].fillna("Unknown")
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,Unknown,invalidemail
2,1003,Anu,Thirty,F,Sales,"48,000",Unknown,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,"48,000",Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,Unknown
96,1097,Mohammed,29,Male,HR,35000,Unknown,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,Unknown,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,Unknown,invalidemail
99,1100,Sara,31,Female,IT,55000,Unknown,2023-01-15,Poor,invalidemail

In [75]:


df["Age"] = df["Age"].replace("Thirty", 30)

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,Unknown,invalidemail
2,1003,Anu,30,F,Sales,"48,000",Unknown,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,"48,000",Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,Unknown
96,1097,Mohammed,29,Male,HR,35000,Unknown,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,Unknown,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,Unknown,invalidemail
99,1100,Sara,31,Female,IT,55000,Unknown,2023-01-15,Poor,invalidemail

In [76]:
df["Age"] = pd.to_numeric(df["Age"]) 
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,Unknown,invalidemail
2,1003,Anu,30,F,Sales,"48,000",Unknown,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,"48,000",Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,Unknown
96,1097,Mohammed,29,Male,HR,35000,Unknown,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,Unknown,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,Unknown,invalidemail
99,1100,Sara,31,Female,IT,55000,Unknown,2023-01-15,Poor,invalidemail

In [77]:
df.dtypes

Employee_Id     int64
Name              str
Age             int64
Gender            str
Department        str
Salary         object
City              str
Joindate          str
Performance       str
Email             str
dtype: object

In [79]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,Unknown,invalidemail
2,1003,Anu,30,F,Sales,"48,000",Unknown,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,"48,000",Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,Unknown
96,1097,Mohammed,29,Male,HR,35000,Unknown,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,Unknown,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,Unknown,invalidemail
99,1100,Sara,31,Female,IT,55000,Unknown,2023-01-15,Poor,invalidemail

In [80]:
df["Salary"] = df["Salary"].astype(str)
df["Salary"] = df["Salary"].str.replace(",", "", regex=False)
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,Unknown,invalidemail
2,1003,Anu,30,F,Sales,48000,Unknown,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,48000,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000,kochi,2024/03/01,good,Unknown
96,1097,Mohammed,29,Male,HR,35000,Unknown,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,Unknown,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000,Kochi,15/02/2022,Unknown,invalidemail
99,1100,Sara,31,Female,IT,55000,Unknown,2023-01-15,Poor,invalidemail

In [81]:
df["Salary"] = pd.to_numeric(df["Salary"]) 
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000.0,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,NaN,Calicut,2023-01-15,Unknown,invalidemail
2,1003,Anu,30,F,Sales,48000.0,Unknown,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000.0,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,48000.0,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.0,kochi,2024/03/01,good,Unknown
96,1097,Mohammed,29,Male,HR,35000.0,Unknown,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,NaN,Unknown,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000.0,Kochi,15/02/2022,Unknown,invalidemail
99,1100,Sara,31,Female,IT,55000.0,Unknown,2023-01-15,Poor,invalidemail

In [82]:
df.dtypes

Employee_Id      int64
Name               str
Age              int64
Gender             str
Department         str
Salary         float64
City               str
Joindate           str
Performance        str
Email              str
dtype: object

In [83]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000.000000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,45766.233766,Calicut,2023-01-15,Unknown,invalidemail
2,1003,Anu,30,F,Sales,48000.000000,Unknown,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000.000000,Calicut,15/02/2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,48000.000000,Unknown,15/02/2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.000000,kochi,2024/03/01,good,Unknown
96,1097,Mohammed,29,Male,HR,35000.000000,Unknown,15/02/2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,45766.233766,Unknown,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000.000000,Kochi,15/02/2022,Unknown,invalidemail
99,1100,Sara,31,Female,IT,55000.000000,Unknown,2023-01-15,Poor,invalidemail

In [85]:
df["Joindate"] = df["Joindate"].str.replace("/", "-", regex=False)
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000.000000,Bangalore,NaN,good,test@mail.com
1,1002,Kiran,31,M,Marketing,45766.233766,Calicut,2023-01-15,Unknown,invalidemail
2,1003,Anu,30,F,Sales,48000.000000,Unknown,NaN,Good,test@mail.com
3,1004,John,27,F,Marketing,35000.000000,Calicut,15-02-2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,48000.000000,Unknown,15-02-2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.000000,kochi,2024-03-01,good,Unknown
96,1097,Mohammed,29,Male,HR,35000.000000,Unknown,15-02-2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,45766.233766,Unknown,NaN,good,test@mail.com
98,1099,Arun,22,Female,IT,42000.000000,Kochi,15-02-2022,Unknown,invalidemail
99,1100,Sara,31,Female,IT,55000.000000,Unknown,2023-01-15,Poor,invalidemail

In [87]:

df["Joindate"] = df["Joindate"].fillna(df["Joindate"].mode()[0])
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000.000000,Bangalore,2023-01-15,good,test@mail.com
1,1002,Kiran,31,M,Marketing,45766.233766,Calicut,2023-01-15,Unknown,invalidemail
2,1003,Anu,30,F,Sales,48000.000000,Unknown,2023-01-15,Good,test@mail.com
3,1004,John,27,F,Marketing,35000.000000,Calicut,15-02-2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,48000.000000,Unknown,15-02-2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.000000,kochi,2024-03-01,good,Unknown
96,1097,Mohammed,29,Male,HR,35000.000000,Unknown,15-02-2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,45766.233766,Unknown,2023-01-15,good,test@mail.com
98,1099,Arun,22,Female,IT,42000.000000,Kochi,15-02-2022,Unknown,invalidemail
99,1100,Sara,31,Female,IT,55000.000000,Unknown,2023-01-15,Poor,invalidemail

In [92]:
df["City"]=df["City"].str.title()
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000.000000,Bangalore,2023-01-15,good,test@mail.com
1,1002,Kiran,31,M,Marketing,45766.233766,Calicut,2023-01-15,Unknown,invalidemail
2,1003,Anu,30,F,Sales,48000.000000,Unknown,2023-01-15,Good,test@mail.com
3,1004,John,27,F,Marketing,35000.000000,Calicut,15-02-2022,good,user@example.com
4,1005,Aisha,25,Unknown,IT,48000.000000,Unknown,15-02-2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.000000,Kochi,2024-03-01,good,Unknown
96,1097,Mohammed,29,Male,HR,35000.000000,Unknown,15-02-2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,45766.233766,Unknown,2023-01-15,good,test@mail.com
98,1099,Arun,22,Female,IT,42000.000000,Kochi,15-02-2022,Unknown,invalidemail
99,1100,Sara,31,Female,IT,55000.000000,Unknown,2023-01-15,Poor,invalidemail

In [93]:
df["Performance"]=df["Performance"].str.title()
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email
0,1001,Rahul,22,Female,Unknown,55000.000000,Bangalore,2023-01-15,Good,test@mail.com
1,1002,Kiran,31,M,Marketing,45766.233766,Calicut,2023-01-15,Unknown,invalidemail
2,1003,Anu,30,F,Sales,48000.000000,Unknown,2023-01-15,Good,test@mail.com
3,1004,John,27,F,Marketing,35000.000000,Calicut,15-02-2022,Good,user@example.com
4,1005,Aisha,25,Unknown,IT,48000.000000,Unknown,15-02-2022,Good,Unknown
...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.000000,Kochi,2024-03-01,Good,Unknown
96,1097,Mohammed,29,Male,HR,35000.000000,Unknown,15-02-2022,Excellent,invalidemail
97,1098,Anu,22,Male,HR,45766.233766,Unknown,2023-01-15,Good,test@mail.com
98,1099,Arun,22,Female,IT,42000.000000,Kochi,15-02-2022,Unknown,invalidemail
99,1100,Sara,31,Female,IT,55000.000000,Unknown,2023-01-15,Poor,invalidemail

In [95]:
df["Performance"].unique()

<StringArray>
['Good ', 'Unknown', 'Good', 'Excellent', 'Poor']
Length: 5, dtype: str

In [97]:
df["Employee_Id"].duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: Employee_Id, Length: 100, dtype: bool

In [98]:
df["salary_category"] = df["Salary"].apply(
    lambda x: "Low" if x < 40000 else "Medium" if x < 50000 else "High"
)
df

,Employee_Id,Name,Age,Gender,Department,Salary,City,Joindate,Performance,Email,salary_category
0,1001,Rahul,22,Female,Unknown,55000.000000,Bangalore,2023-01-15,Good,test@mail.com,High
1,1002,Kiran,31,M,Marketing,45766.233766,Calicut,2023-01-15,Unknown,invalidemail,Medium
2,1003,Anu,30,F,Sales,48000.000000,Unknown,2023-01-15,Good,test@mail.com,Medium
3,1004,John,27,F,Marketing,35000.000000,Calicut,15-02-2022,Good,user@example.com,Low
4,1005,Aisha,25,Unknown,IT,48000.000000,Unknown,15-02-2022,Good,Unknown,Medium
...,...,...,...,...,...,...,...,...,...,...,...
95,1096,Anu,27,Male,Sales,42000.000000,Kochi,2024-03-01,Good,Unknown,Medium
96,1097,Mohammed,29,Male,HR,35000.000000,Unknown,15-02-2022,Excellent,invalidemail,Low
97,1098,Anu,22,Male,HR,45766.233766,Unknown,2023-01-15,Good,test@mail.com,Medium
98,1099,Arun,22,Female,IT,42000.000000,Kochi,15-02-2022,Unknown,invalidemail,Medium
99,1100,Sara,31,Female,IT,55000.000000,Unknown,2023-01-15,Poor,invalidemail,High

In [100]:
df.dtypes

Employee_Id          int64
Name                   str
Age                  int64
Gender                 str
Department             str
Salary             float64
City                   str
Joindate               str
Performance            str
Email                  str
salary_category        str
dtype: object