In [37]:
import  pandas as pd
movie=[
       [101, "Inception", "Sci-Fi", 8.8, 2010],
    [102, "Avatar", "Action", 7.9, 2009],
    [103, "Titanic", "Romance", 7.9, 1997],
    [104, "Joker", "Drama", 8.4, 2019]
    
]
df=pd.DataFrame(movie,columns=['Movie_id','Movie_name','Genre','Rating','Release_Year '])
df

   Movie_id Movie_name    Genre  Rating  Release_Year
0       101  Inception   Sci-Fi     8.8           2010
1       102     Avatar   Action     7.9           2009
2       103    Titanic  Romance     7.9           1997
3       104      Joker    Drama     8.4           2019

In [38]:
movie={'Movie_id':[101,102,103,104],
       'Movie_name':['Inception','Avatar','Titanic','Joker'],
       'Genre':['Sci-Fi','Action','Romance','Drama'],
       'Rating':[8.8,7.9,7.9,8.4],
       'Release_Year':[2010,2009,1997,2019]
      }
df=pd.DataFrame(movie)
df

   Movie_id Movie_name    Genre  Rating  Release_Year
0       101  Inception   Sci-Fi     8.8          2010
1       102     Avatar   Action     7.9          2009
2       103    Titanic  Romance     7.9          1997
3       104      Joker    Drama     8.4          2019

In [39]:
movie= [
    {"Movie_ID": 101, "Movie_Name": "Inception", "Genre": "Sci-Fi", "Rating": 8.8, "Release_Year": 2010},
    {"Movie_ID": 102, "Movie_Name": "Avatar", "Genre": "Action", "Rating": 7.9, "Release_Year": 2009},
    {"Movie_ID": 103, "Movie_Name": "Titanic", "Genre": "Romance", "Rating": 7.9, "Release_Year": 1997},
    {"Movie_ID": 104, "Movie_Name": "Joker", "Genre": "Drama", "Rating": 8.4, "Release_Year": 2019}
]
df=pd.DataFrame(movie)
df

   Movie_ID Movie_Name    Genre  Rating  Release_Year
0       101  Inception   Sci-Fi     8.8          2010
1       102     Avatar   Action     7.9          2009
2       103    Titanic  Romance     7.9          1997
3       104      Joker    Drama     8.4          2019

In [40]:
tit=pd.read_csv(r"C:\Users\ANSHIKA\Downloads\Titanic-Dataset.csv")
df

   Movie_ID Movie_Name    Genre  Rating  Release_Year
0       101  Inception   Sci-Fi     8.8          2010
1       102     Avatar   Action     7.9          2009
2       103    Titanic  Romance     7.9          1997
3       104      Joker    Drama     8.4          2019

In [41]:
tit.ndim

2

In [42]:
tit.shape

(891, 12)

In [43]:
tit.size

10692

In [44]:
tit.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [45]:
tit.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [46]:
tit.head(8)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [47]:
tit.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [48]:
tit.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [49]:
df.describe(include='object')

C:\Users\ANSHIKA\AppData\Local\Temp\ipykernel_13764\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

       Movie_Name   Genre
count           4       4
unique          4       4
top     Inception  Sci-Fi
freq            1       1

In [50]:
df.describe()

         Movie_ID   Rating  Release_Year
count    4.000000  4.00000      4.000000
mean   102.500000  8.25000   2008.750000
std      1.290994  0.43589      9.032349
min    101.000000  7.90000   1997.000000
25%    101.750000  7.90000   2006.000000
50%    102.500000  8.15000   2009.500000
75%    103.250000  8.50000   2012.250000
max    104.000000  8.80000   2019.000000

In [51]:
tit.iloc[1:][['PassengerId','Name','Age','Sex','Survived']]

,PassengerId,Name,Age,Sex,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,female,1
2,3,"Heikkinen, Miss. Laina",26.0,female,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,female,1
4,5,"Allen, Mr. William Henry",35.0,male,0
5,6,"Moran, Mr. James",NaN,male,0
...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",27.0,male,0
887,888,"Graham, Miss. Margaret Edith",19.0,female,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,female,0
889,890,"Behr, Mr. Karl Howell",26.0,male,1
890,891,"Dooley, Mr. Patrick",32.0,male,0

In [52]:
df.iloc[5:16]

Empty DataFrame
Columns: [Movie_ID, Movie_Name, Genre, Rating, Release_Year]
Index: []

In [61]:
df.loc[20:30, ['Name', 'Fare']]

KeyError: "None of [Index(['Name', 'Fare'], dtype='str')] are in the [columns]"

In [54]:
tit.iloc[1:11]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S

In [ ]:
df.iloc[-5:]

In [55]:
df.iloc[3:13]

   Movie_ID Movie_Name  Genre  Rating  Release_Year
3       104      Joker  Drama     8.4          2019

In [ ]:
df.iloc[1:5]

In [56]:
tit["Family_Size"] = tit["SibSp"] + tit["Parch"]
tit

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0